PIXCRATE/core/controllers/CrateController.php
<?php

require_once("core/controllers/CFoundation.php");

class CrateController extends CFoundation {
  public function actionIndex() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/crate");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }

  public function actionImage() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/image");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }

  public function actionUpload() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/images/addImage");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  
  public function actionDelete_image() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/images/deleteImage");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  
  public function actionEdit_image() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/images/editImage");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
}


?>

PIXCRATE/core/controllers/ProfileController.php
<?php

require_once("core/controllers/CFoundation.php");

class ProfileController extends CFoundation {
  public function actionIndex() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/profile");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  public function actionCrates() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/crates");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  public function actionCreate_repository() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/crates/addCrate");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  public function actionEdit_repository() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/crates/editCrate");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  public function actionDelete_repository() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/crates/deleteCrate");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
  public function actionProfile_image() {
    require CFGList::path_sheet["snippet_path"]."begin.php";
    parent::render("user-side/profileimage");
    require CFGList::path_sheet["snippet_path"]."end.php";
  }
}


?>

PIXCRATE/core/views/user-side/crate.php
<?php

    require_once "core/utils.php";

    require_once "core/hyppos/repository.php";
    require_once "core/models/repositorymodel.php";

    require_once "core/hyppos/repositoryuser.php";
    require_once "core/models/repositoryusermodel.php";

    require_once "core/hyppos/image.php";
    require_once "core/models/imagemodel.php";

    Utils::startSession()->checkSession();

    $repositoryId= isset($_GET["id"])? $_GET["id"]: null;

    if(isset($repositoryId)) {
        $crate = new Repository(["repositoryId" => $repositoryId]);
        $thisCrate = RepositoryModel::load($crate);

        $link = new Repository_Has_User(array("user_email" => $_SESSION["email"], "repository_repositoryId" => $repositoryId));
        $linkedCrate = RepositoryUserModel::load($link);

        if($linkedCrate["permission"] == "OWNER") {
            $visibility = "";
        } else {
            $visibility = "PUBLIC";
        }

        $image = new Image([
            "repository_repositoryId" => $repositoryId,
            "visibility" => $visibility
        ]);
        $allImagesFromRep = ImageModel::loadAll($image);
?>

<div class="row no-gutters pixcrate-std-red">
    <div class="col-12 col-sm-2">
        <nav class="navbar w-100">
            <span class="navbar-brand text-white text-lg m-auto">Pixcrate</span>
        </nav>
    </div>
    <div class="col-12 col-sm-8">
        <nav class="navbar">
            <form class="form-inline d-flex flex-nowrap h-75 ml-auto mt-1" method="get" action=<?=ABS_PATH . "explore"?>>
                <input class="form-control rounded-0 pixcrate-rounded-left border-0 box-shadow-none text-truncate" type="search" placeholder="Search" 
                aria-label="Search" name="search" pattern="[A-Za-z0-9]{1,}" title="One character" required>
                <button class="my-2 my-sm-0 rounded-0 border-0 pixcrate-search-btn bg-white pixcrate-rounded-right" type="submit">
                    <i class="material-icons d-block mt-1 md-24">search</i>
                </button>
            </form>
        </nav>
    </div>
    <div class="col-12 col-sm-2"></div>
</div>
<div class="row no-gutters pixcrate-gray-light-20">
    <div class="col-12 col-sm-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb background-transparent my-auto ml-5">
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "home"?> class="underline-none pixcrate-text-dark">Home</a></li>
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "profile"?> class="underline-none pixcrate-text-dark">Profile</a></li>
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "profile/crates"?> class="underline-none pixcrate-text-dark">Crates</a></li>
                <li class="breadcrumb-item active " aria-current="page"><?=$thisCrate["name"]?></li>
            </ol>
        </nav>
    </div>
</div>
<div class="row no-gutters pixcrate-gray-light-10">
    <div class="col-12 col-sm-12">
        <a href=<?=ABS_PATH . "crate/upload?crate=" . $thisCrate["repositoryId"]?> class="btn std-button pixcrate-std-red my-2 ml-4">
            <div class="py-1">
                <i class="material-icons text-white d-inline-block align-middle">file_upload</i>
                <span class="text-white d-inline-block align-middle ml-1">Upload an image</span>
            </div>
        </a>
    </div>
</div>
<div class="row no-gutters m-auto" style="max-width: 1350px;">
    <div class="col-12 col-sm-12 d-flex flex-wrap">
        <?php 
            if(sizeof($allImagesFromRep) > 0) {
                $i= 1;
                foreach($allImagesFromRep as $row) {
        ?>
            <div class="card mx-auto mt-4 " style="width: 640px; height: 360px;">
                <form action=<?=ABS_PATH . 'crate/image'?> method="get" class="text-center underline-none overflow-hide pixcrate-border-3 rounded-top">
                    <input type="hidden" name="id" value=<?=$row["imageId"]?>>
                    <button type="submit" class="btn p-0 pixcrate-image-blur d-block w-100">
                        <img src="<?=$row["url"]?>" class="card-img-top img-fluid border-0 ">
                    </button>
                </form>
                <div class="card-footer pixcrate-gray-light-8 border-0 pixcrate-border-3 d-flex">
                    
                    <div class="d-flex mr-2">
                        <div class="m-1 p-1">
                            <span class="w-100 h-100 text-truncate center-align pixcrate-text-dark">
                                <?=$row["title"]?>
                            </span>
                        </div>
                        <div class="m-1 p-1 text-white">      
                            <span class="text-center text-truncate d-inline center-align align-middle badge badge-secondary pixcrate-std-red">
                                <?=$row["visibility"]?>
                            </span>
                        </div>
                        <button class="btn pixcrate-pane-button background-transparent pixcrate-text-dark mx-1 p-1">
                            <span class="text-center text-truncate d-inline align-middle">
                                <?=$row["likes"]?>
                            </span>
                            <i class="material-icons align-middle">thumb_up</i>
                        </button>
                        <button class="btn pixcrate-pane-button background-transparent pixcrate-text-dark mx-1 p-1">
                            <span class="text-center text-truncate d-inline center-align align-middle">
                                <?=$row["reposts"]?>
                            </span>
                            <i class="material-icons d-inline align-middle">repeat</i>
                        </button>
                    </div>
                    <?php
                    if($linkedCrate["permission"] == "OWNER") {
                    ?>
                        <div>
                            <a href=<?=ABS_PATH . "crate/delete_image?id=" . $row["imageId"]?> class="btn background-transparent pixcrate-pane-button">
                                <i class="material-icons d-inline align-middle">delete</i>
                            </a>
                        </div>

                        <div>
                            <a href=<?=ABS_PATH . "crate/edit_image?id=" . $row["imageId"]?> class="btn background-transparent pixcrate-pane-button">
                                <i class="material-icons d-inline align-middle">edit</i>
                            </a>
                        </div>     
                    <?php
                    }
                    ?>
                </div>
            </div>
        <?php
                }
            } else {
                echo 
                    "<div class='d-flex mx-auto mt-5 w-50 flex-wrap center-align'>" .
                        "<h1 class='mx-auto'>There's no images here!</h1>" .
                        "<p class='mx-auto my-2 text-muted'>Try to upload some images by clicking the \"Upload an image\" buttom above.</p>" .
                    "</div>"
                ;
            }
        ?>
    </div>
</div>
            
<div class="row no-gutters py-3">
    <div class="col-12 col-sm-12"></div>
</div>

<?php
            
    } else {
        header("Location:" . ABS_PATH . "missing");
    }

?>

PIXCRATE/core/views/user-side/home.php
<head>
    <link rel="stylesheet" href="<?=ABS_PATH . CFGList::path_sheet['style_path']?>home.css">
    <script src="<?=ABS_PATH . CFGList::path_sheet['script_path']?>main/home.js"></script>
</head>

<?php
require_once "core/utils.php";

require_once "core/models/usermodel.php";
require_once "core/hyppos/user.php";

require_once "core/hyppos/repository.php";
require_once "core/models/repositorymodel.php";

require_once "core/hyppos/repositoryuser.php";
require_once "core/models/repositoryusermodel.php";

require_once "core/hyppos/image.php";
require_once "core/models/imagemodel.php";

Utils::startSession()->checkSession();
$user = new User(array("email" => $_SESSION["email"]));
$loadedUser = UserModel::load($user);

$profileImage = $loadedUser["profileImage"];
$visibility = "";

$obj = new Repository_Has_User([
    "user_email" => $_SESSION["email"]
]);
$resultLinks = RepositoryUserModel::loadAll($obj);

$resultCrates = [];
$resultImages = [];

foreach ($resultLinks as $row) {

    $obj = new Repository([
        "repositoryId" => $row["repository_repositoryId"]
    ]);
    $result = RepositoryModel::load($obj);

    array_push($resultCrates, $result);
}

?>
<div class="row no-gutters pixcrate-std-red">
    <div class="col-12 col-sm-2">
        <nav class="navbar w-100">
            <span class="navbar-brand text-white text-lg m-auto">Pixcrate</span>
        </nav>
    </div>
    <div class="col-12 col-sm-8">
        <nav class="navbar">
            <form class="form-inline d-flex flex-nowrap h-75 ml-auto mt-1" method="get" action=<?=ABS_PATH . "explore"?>>
                <input class="form-control rounded-0 pixcrate-rounded-left border-0 box-shadow-none text-truncate" type="search" placeholder="Search" 
                aria-label="Search" name="search" pattern="[A-Za-z0-9]{1,}" title="One character" required>
                <button class="my-2 my-sm-0 rounded-0 border-0 pixcrate-search-btn bg-white pixcrate-rounded-right" type="submit">
                    <i class="material-icons d-block mt-1 md-24">search</i>
                </button>
            </form>
        </nav>
    </div>
    <div class="col-12 col-sm-2 pixcrate-std-red"></div>
</div>
<div class="row no-gutters border-bottom pixcrate-gray-light-12 border-0">
    <div class="col-12">
        <div class="card border-0 background-transparent">
            <div class="card-body d-flex border-left py-4 px-5">
                <a href="<?=ABS_PATH . "profile"?>" class="rounded-circle overflow-hide" id="profileImageHolder">
                    <img src=<?=$profileImage?> alt="" height=110 width=110 class="m-auto d-block position-relative" id="profileImage">
                </a>
                <div class="pt-4 text-truncate d-inline-block pixcrate-text-dark">
                    <span class="align-middle underline-none d-block my-auto mx-4"><?=$_SESSION["username"]?></span>
                    <span class="align-middle d-block font-weight-bold mx-4 pixcrate-clock"></span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row no-gutters pixcrate-gray-light-4">
    <div class="col-12 col-sm-2">
        <div class="d-flex m-auto pixcrate-gray-light-4 border-0 text-truncate">
            <a href="<?=ABS_PATH . "profile"?>" class="pixcrate-pane-button text-center underline-none text-truncate py-1">
                <i class="material-icons d-block">person</i>
                <span class="d-block">Profile</span>
            </a>
            <a href="<?=ABS_PATH . "profile/crates"?>" class="pixcrate-pane-button text-center underline-none text-truncate py-1">
                <i class="material-icons d-block">inbox</i>
                <span class="d-block">Crates</span>
            </a>
            <?php
                if($_SESSION["serveradmin"] != 0) {
            ?>
                    <a href="<?=ABS_PATH . "management"?>" class="pixcrate-pane-button text-center underline-none text-truncate py-1">
                        <i class="material-icons d-block">build</i>
                        <span class="d-block">Management</span>
                    </a> 
            <?php 
                }
            ?>
        </div>
    </div>
    <div class="col-12 col-sm-8"> 
    </div>
    <div class="col-12 col-sm-2">
        <div class="d-flex pixcrate-gray-light-4 rounded-bottom border-0">
            <a href="<?=ABS_PATH . "about"?>" class="pixcrate-pane-button text-center underline-none text-truncate py-1">
                <i class="material-icons d-block">help_outline</i>
                <span class="d-block">About</span>
            </a>
            <a href="<?=ABS_PATH . "logout"?>" class="pixcrate-pane-button text-center underline-none text-truncate py-1">
                <i class="material-icons d-block">exit_to_app</i>
                <span class="d-block">Exit</span>
            </a>
        </div>
    </div>
</div>

<div class="row no-gutters">
    <div class="col-12 col-sm-2"></div>
    <div class="col-12 col-sm-8">
        <?php
        include_once "core/views/public-side/results/crateresults.php";
        ?>
    </div>
    <div class="col-12 col-sm-2"></div>
</div>

PIXCRATE/core/views/user-side/image.php
<?php
require_once "core/utils.php";

require_once "core/hyppos/image.php";
require_once "core/models/imagemodel.php";

require_once "core/hyppos/repository.php";
require_once "core/models/repositorymodel.php";

Utils::startSession()->checkSession();
$imageId= isset($_GET["id"])? $_GET["id"]: null;
if(isset($imageId)) {
    $image = new Image(["imageId" => $imageId]);
    $currentImage = ImageModel::load($image);
    $crate = new Repository(["repositoryId" => $currentImage["repository_repositoryId"]]);
    $currentCrate = RepositoryModel::load($crate);
    if(sizeof($currentImage) < 1){
        header("Location:" . ABS_PATH . "missing/404image");
    } else { 
?>
<div class="row no-gutters pixcrate-std-red">
    <div class="col-12 col-sm-2">
        <nav class="navbar w-100">
            <span class="navbar-brand text-white text-lg m-auto">Pixcrate</span>
        </nav>
    </div>
    <div class="col-12 col-sm-8">
        <nav class="navbar">
            <form class="form-inline d-flex flex-nowrap h-75 ml-auto mt-1" method="get" action=<?=ABS_PATH . "explore"?>>
                <input class="form-control rounded-0 pixcrate-rounded-left border-0 box-shadow-none text-truncate" type="search" placeholder="Search" 
                aria-label="Search" name="search" pattern="[A-Za-z0-9]{1,}" title="One character" required>
                <button class="my-2 my-sm-0 rounded-0 border-0 pixcrate-search-btn bg-white pixcrate-rounded-right" type="submit">
                    <i class="material-icons d-block mt-1 md-24">search</i>
                </button>
            </form>
        </nav>
    </div>
    <div class="col-12 col-sm-2"></div>
</div>
<div class="row no-gutters pixcrate-gray-light-20">
    <div class="col-12 col-sm-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb background-transparent my-auto ml-5">
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "home"?> class="underline-none pixcrate-text-dark">Home</a></li>
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "profile"?> class="underline-none pixcrate-text-dark">Profile</a></li>
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "profile/crates"?> class="underline-none pixcrate-text-dark">Crates</a></li>
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "crate?id=" . $currentCrate["repositoryId"]?> class="underline-none pixcrate-text-dark"><?=$currentCrate["name"]?></a></li>
                <li class="breadcrumb-item active " aria-current="page"><?=$currentImage["title"]?></li>
            </ol>
        </nav>
    </div>
</div>
<div class="row no-gutters">
    <div class="col-12 col-sm-2"></div>
    <div class="col-12 col-sm-8">
        <div class="card mx-auto my-5 underline-none pixcrate-border-3 rounded-top w-75 h-75">
            <div class="card-header pixcrate-std-red border-0">
                <h5 class="text-center text-white font-weight-normal m-0"><?=$currentImage["title"]?></h5>
            </div>
            <div class="overflow-hide">
                <img src="<?=$currentImage["url"]?>" class="card-img-top img-fluid rounded-0">
            </div>
            <div class="card-body pixcrate-gray-light-6 border-bottom px-4">
                <p class="center-align"><?=$currentImage["description"]?></p>
            </div>
            <div class="card-footer pixcrate-gray-light-8 border-0 pixcrate-border-3 d-flex flex-wrap w-100">
                <div class="d-flex mr-2">
                    <button class="btn pixcrate-pane-button background-transparent pixcrate-text-dark mx-1 p-1">
                        <span class="text-center text-truncate d-inline align-middle">
                            <?=$currentImage["likes"]?>
                        </span>
                        <i class="material-icons align-middle">thumb_up</i>
                    </button>
                </div>
                <div class="d-flex">
                    <button class="btn pixcrate-pane-button background-transparent pixcrate-text-dark mx-1 p-1">
                        <span class="text-center text-truncate d-inline center-align align-middle">
                            <?=$currentImage["reposts"]?>
                        </span>
                        <i class="material-icons d-inline align-middle">repeat</i>
                    </button>
                </div>
                <div class="background-transparent mx-1 p-1">      
                    <span class="text-center text-truncate d-inline center-align align-middle pixcrate-text-dark">
                        <?=$currentImage["date"]?>
                    </span>
                </div>
                <div class="p-1 text-white">      
                    <span class="text-center text-truncate d-inline center-align align-middle badge badge-secondary pixcrate-std-red">
                        <?=$currentImage["visibility"]?>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-2"></div>
</div>
<?php 
    }
}
?>

PIXCRATE/core/views/user-side/profile.php
<head>
    <script src="<?=ABS_PATH . CFGList::path_sheet['script_path']?>main/profile.js"></script>
</head>

<?php 
require_once "core/utils.php";

require_once "core/models/usermodel.php";
require_once "core/hyppos/user.php";

require_once "core/hyppos/repository.php";
require_once "core/models/repositorymodel.php";

require_once "core/hyppos/repositoryuser.php";
require_once "core/models/repositoryusermodel.php";

require_once "core/hyppos/image.php";
require_once "core/models/imagemodel.php";


Utils::startSession()->checkSession();
$user = new User(array("email" => $_SESSION["email"]));
$loadedUser = UserModel::load($user);
$profileImage = $loadedUser["profileImage"];

$link = new Repository_Has_User(array("user_email" => $_SESSION["email"]));
$linkedCrates = RepositoryUserModel::loadAll($link);

$totalImages = 0;
$totalOwnedImages = 0;

foreach ($linkedCrates as $row) {

    if($row["permission"] == "OWNER") {
        $visibility = "";
    } else {
        $visibility = "PUBLIC";
    }
    
    $image = new Image([
        "repository_repositoryId" => $row["repository_repositoryId"],
        "visibility" => $visibility
    ]);

    if($row["permission"] == "OWNER") {
        $allImagesFromRep = ImageModel::loadAll($image);
        $totalOwnedImages+= sizeof($allImagesFromRep);
    } 

    $allImagesFromRep = ImageModel::loadAll($image);
    $totalImages+= sizeof($allImagesFromRep);
}

?>

<div class="row no-gutters pixcrate-std-red">
    <div class="col-12 col-sm-2">
        <nav class="navbar w-100">
            <span class="navbar-brand text-white text-lg m-auto">Pixcrate</span>
        </nav>
    </div>
    <div class="col-12 col-sm-8">
        <nav class="navbar">
            <form class="form-inline d-flex flex-nowrap h-75 ml-auto mt-1" method="get" action=<?=ABS_PATH . "explore"?>>
                <input class="form-control rounded-0 pixcrate-rounded-left border-0 box-shadow-none text-truncate" type="search" placeholder="Search" 
                aria-label="Search" name="search" pattern="[A-Za-z0-9]{1,}" title="One character" required>
                <button class="my-2 my-sm-0 rounded-0 border-0 pixcrate-search-btn bg-white pixcrate-rounded-right" type="submit">
                    <i class="material-icons d-block mt-1 md-24">search</i>
                </button>
            </form>
        </nav>
    </div>
    <div class="col-12 col-sm-2"></div>
</div>
<div class="row no-gutters pixcrate-gray-light-20">
    <div class="col-12 col-sm-4">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb background-transparent my-auto ml-5">
                <li class="breadcrumb-item"><a href=<?=ABS_PATH . "home"?> class="underline-none pixcrate-text-dark">Home</a></li>
                <li class="breadcrumb-item active " aria-current="page">Profile</li>
            </ol>
        </nav>
    </div>
    <div class="col-12 col-sm-4">
    </div>
    <div class="col-12 col-sm-4"></div>
</div>
<div class="row no-gutters pixcrate-gray-light-6">
    <div class="col-12 col-sm-4 d-flex flex-wrap pixcrate-gray-light-4">
        <div class="mt-6 mb-5 ml-6 overflow-hide">
            <?php
                if(isset($profileImage) && $profileImage != ""){
            ?>
                <img src=<?=$profileImage?> alt="profile-image" class="pixcrate-circle d-inline-block m-auto" width=200 height=200>
            <?php
                } else {
            ?>
                <img src=<?=CFGList::path_sheet["img_path"]."images/desert.jpg"?> alt="profile-image" class="pixcrate-circle d-inline-block m-auto" width=200 height=200>
            <?php
                }
            ?>
        </div>
        <div class="card background-transparent border-0 mt-6 mb-5 ml-5">
            <div class="card-body">
                <h2 class="font-weight-bold pixcrate-text-dark pixcrate-clock"></h2>
                <h4 class="card-title pixcrate-text-dark"><?=$loadedUser["username"]?></h5>
                <h5 class="card-subtitle mb-2 text-muted"><?=$loadedUser["name"]?> <?=$loadedUser["surname"]?></h6>
                <h6 class="card-subtitle mb-2 text-muted font-size-8">Birth date: <?=date("d-m-Y", strtotime($loadedUser["birth"]))?></h6>
                <div>
                    <a href=<?=ABS_PATH . "password"?> class="card-link d-block" id="changePasswordLink">Change password</a>
                    <a href=<?=ABS_PATH . "profile/profile_image"?> class="card-link d-block m-0" id="uploadProfileImageLink">Upload profile image</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-5 border-right pixcrate-border-dark">
        <div class="ml-4 mt-3 d-block">
            <a href=<?=ABS_PATH . "profile/crates"?> class="btn std-button pixcrate-std-red py-3 px-5 m-2" id="cratesLink"><span class="text-white">Crates</span></a>
            <a href=<?=ABS_PATH . "logout"?> class="btn std-button pixcrate-std-red py-3 px-5 m-2" id="logoutLink"><span class="text-white">Log out</span></a>
            <?php
                if(isset($loadedUser["apikey"]) && $loadedUser["apikey"] != " ") {
            ?>
                    <button class="btn std-button pixcrate-text-dark pixcrate-gray-light-30 border-0 rounded-0 pixcrate-rounded-left pixcrate-rounded-right py-2 px-4 m-2" 
                    type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" id="accordion">
                        <i class="material-icons d-inline-block my-2">remove_red_eye</i>
                    </button>
            <?php
                }
            ?>
            <div id="collapseOne" class="collapse input-has-border pixcrate-rounded-right pixcrate-rounded-left pixcrate-gray-light-10 text-center ml-2 mr-4 text-truncate" aria-labelledby="headingOne" data-parent="#accordion">
                <span class="text-muted d-inline-block pt-1">
                    <?=$loadedUser["apikey"]?>
                </span>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-3 pixcrate-gray-light-4">
        <div class="p-5 w-100 h-100 pixcrate-text-dark pixcrate-border-dark pixcrate-gray-light-4" id="hintHolder">
            <p id="hintParagraph"></p>
        </div>
    </div>
</div>

<div class="row no-gutters pixcrate-gray-light-4 pixcrate-text-dark d-flex">
    <div class="text-center py-5 px-5 mx-auto">
        <i class="material-icons">inbox</i>
        <h1 class="font-weight-bold m-0 d-inline">
            <?=sizeof($linkedCrates)?>
        </h1>
        <span class="d-inline h3">links</span>
        <p class="text-muted">with crates overall</p>
    </div>
    <div class="text-center py-5 px-5 mx-auto">
        <i class="material-icons">photo</i>
        <h1 class="font-weight-bold m-0 d-inline">
            <?=$totalImages?>
        </h1>
        <span class="d-inline h3">links</span>
        <p class="text-muted">with images overall</p>
    </div>
    <div class="text-center py-5 px-5 mx-auto">
        <i class="material-icons">photo</i>
        <h1 class="font-weight-bold m-0 d-inline">
            <?=$totalOwnedImages?>
        </h1>
        <span class="d-inline h3">images</span>
        <p class="text-muted">owned overall</p>
    </div>
    <div class=""></div>
</div>

PIXCRATE/core/views/user-side/verify.php
<?php
require_once "core/hyppos/user.php";
require_once "core/models/usermodel.php";

$email= isset($_GET["email"])? $_GET["email"]: null;
$hash= isset($_GET["hash"])? $_GET["hash"]: null;

if( (isset($email) && $email != "") && (isset($hash) && $hash != "") ) {
    $user = new User(["email" => $email]);
    $result = UserModel::load($user);
    if(sizeof($result) > 0 && (isset($result["hash"]) && $result["hash"] != "") ) {
        if($hash == $result["hash"]) {
            $user = new User([
                "email" => $email,
                "verified" => true
            ]);
            UserModel::update($user, " WHERE email=?");
            $result = UserModel::load($user);
            if(sizeof($result) > 0) {
                $user = new User([
                    "email" => $email,
                    "hash" => " "
                ]);
                UserModel::update($user, " WHERE email=?");
                echo "<h1 class='text-center mx-auto mt-4'>User verified correctly.</h1>";
            }
        } else {
            echo "<h1 class='text-center mx-auto mt-4'>Error: User could not be verified.</h1>";
        }
    }
} else {
    header("Location: " . ABS_PATH . "home");
}
?>